source: app
destination: public

include: [.htaccess]

permalink: /:categories/:title/
highlighter: pygments

defaults:
-   scope:
        path: 'journal'
        type: 'posts'
    values:
        layout: 'post'

-   scope:
        path: 'journal'
        type: 'drafts'
    values:
        layout: 'post'

prose:
    rooturl: 'app/journal'
    media: 'app/assets/images/journal'
    ignore:
        -   index.html
        -   _data
        -   _includes
        -   _layouts
        -   about
        -   collection
        -   contact
        -   press
        -   stockist
        -   .htaccess
        -   404.html
        -   apple-touch-icon-114x114.png
        -   apple-touch-icon-57x57.png
        -   apple-touch-icon-72x72.png
        -   apple-touch-icon.png
        -   favicon.ico
        -   favicon.png
        -   og-image.png
        -   robots.txt
        -   /app/assets/css
        -   /app/assets/js
        -   /app/assets/vendor
        -   /app/assets/videos
        -   /app/assets/images/components
        -   /app/assets/images/storybook
    metadata:
        _posts:
            -   name: 'language'
                field:
                    element: 'select'
                    label: 'language'
                    help: 'Select the language of this post (defaults to English). This affects the fonts used.'
                    options:
                        -   name: 'English'
                            value: 'en'
                        -   name: 'French'
                            value: 'fr'
                        -   name: 'Japanese'
                            value: 'jp'
