url: http://vestigestory.com
source: app
destination: public

permalink: /:categories/:title/
highlighter: pygments

defaults:
-   scope:
        path: 'journal'
        type: 'posts'
    values:
        layout: 'post'

-   scope:
        path: 'journal'
        type: 'drafts'
    values:
        layout: 'post'

prose:
    rooturl: 'app'
    media: 'app/assets/images/journal'
    ignore:
        -   style-guide.md
        -   index.html
        -   _data
        -   _includes
        -   _layouts
        -   about
        -   collection
        -   contact
        -   press
        -   stockist
        -   404.html
        -   500.html
        -   apple-touch-icon-114x114.png
        -   apple-touch-icon-57x57.png
        -   apple-touch-icon-72x72.png
        -   apple-touch-icon.png
        -   favicon.ico
        -   favicon.png
        -   og-image.png
        -   robots.txt
        -   /app/assets/css
        -   /app/assets/js
        -   /app/assets/vendor
        -   /app/assets/videos
        -   /app/assets/images/components
        -   /app/assets/images/storybook
    metadata:
        app/journal/_posts: &metadata
            -   name: 'title'
                field:
                    element: 'text'
                    label: 'Title'
                    help: 'This is the title which appears in the cover of the post. The title also appears as the tab name of the browser.'
                    placeholder: 'Change the post title here'
                    type: text

            -   name: 'published'
                field:
                    element: 'checkbox'
                    label: 'Specify whether this post is available on the live site.'
                    help: 'Uncheck this if you do not want this post published for the time being. You can reenable this at a later time.'
                    value: true

            -   name: 'author'
                field:
                    element: 'select'
                    label: 'Author'
                    help: 'Select the author of this post.'
                    options:
                        -   name: 'Aileen'
                            value: 'aileen'

            -   name: 'cover'
                field:
                    element: 'text'
                    label: 'Cover Photo'
                    help: 'Relative path to the cover photo in the following format: /assets/images/journal/{year}/{month}/{file-name} (i.e. /assets/images/journal/2015/04/cover.jpg).'
                    value: '/assets/images/journal/'
                    placeholder: '/assets/images/journal/{year}/{month}/{file-name}'

            -   name: 'language'
                field:
                    element: 'select'
                    label: 'Language'
                    help: 'Select the language of this post. This affects the fonts used.'
                    options:
                        -   name: 'English'
                            value: 'en'
                        -   name: 'French'
                            value: 'fr'
                        -   name: 'Japanese'
                            value: 'jp'

        app/journal/_drafts:
            -   name: 'title'
                field:
                    element: 'text'
                    label: 'Title'
                    help: 'This is the title which appears in the cover of the post. The title also appears as the tab name of the browser.'
                    placeholder: 'Change the post title here'
                    type: text

            -   name: 'published'
                field:
                    element: 'hidden'
                    value: true

            -   name: 'author'
                field:
                    element: 'select'
                    label: 'Author'
                    help: 'Select the author of this post.'
                    options:
                        -   name: 'Aileen'
                            value: 'aileen'

            -   name: 'cover'
                field:
                    element: 'text'
                    label: 'Cover Photo'
                    help: 'Relative path to the cover photo in the following format: /assets/images/journal/{year}/{month}/{file-name} (i.e. /assets/images/journal/2015/04/cover.jpg).'
                    value: '/assets/images/journal/'
                    placeholder: '/assets/images/journal/{year}/{month}/{file-name}'

            -   name: 'language'
                field:
                    element: 'select'
                    label: 'Language'
                    help: 'Select the language of this post. This affects the fonts used.'
                    options:
                        -   name: 'English'
                            value: 'en'
                        -   name: 'French'
                            value: 'fr'
                        -   name: 'Japanese'
                            value: 'jp'
