source: app
destination: public

include: [.htaccess]
keep_files: [assets]

permalink: /:categories/:title/
highlighter: pygments

info_email: info@vestigestory.com
accounts_email: accounts@vestigestory.com
press_email: press@vestigestory.com
facebook: https://www.facebook.com/vestigestory
instagram: https://instagram.com/vestige_story/
pinterest: https://www.pinterest.com/vestigestory/

defaults:
-   scope:
        path: 'journal'
        type: 'posts'
    values:
        layout: 'post'
